###################################
server.port=15000
##################mysql##################
regood.mysql.ip=127.0.0.1
regood.mysql.port=3306
regood.mysql.db=regood
regood.mysql.username=root
regood.mysql.password=123456
##################redis##################
regood.redis.host=127.0.0.1
regood.redis.port=6379
regood.redis.index=2
regood.redis.password=123456
##################wechat##################
regood.wechat.appid=
regood.wechat.appSecret=
regood.wechat.redirectUri=
##################url##################
regood.url.front=http://localhost:11000
regood.url.backend=http://localhost:15000
##################oss##################
regood.oss.type=3
regood.oss.minio.endpoint=http://1.14.68.127:9090/
regood.oss.minio.bucketName=regood
regood.oss.minio.accessKey=3hc4lzYjDGpj78rp16sl
regood.oss.minio.secretKey=xbU8RlByYQFKxgFxJVJCA4YrhSTj5VIJPSP63u1l
regood.oss.aliyun.endpoint=
regood.oss.aliyun.accessKey=
regood.oss.aliyun.secretKey=
regood.oss.aliyun.bucketName=
regood.oss.local.path=D:/project/oss/regood/
##################email##################
regood.mail.host=smtp.qq.com
regood.mail.port=587
regood.mail.username=2770063826@qq.com
regood.mail.password=xkcljwugxvxsdhbf
###################MQ##################
regood.rabbitmq.host=1.14.68.127
regood.rabbitmq.port=5672
regood.rabbitmq.username=jixer666rabbitmq
regood.rabbitmq.password=jixer666rabbitmq
regood.rabbitmq.concurrency=5
regood.rabbitmq.maxConcurrency=10
regood.rabbitmq.prefetch=1
regood.rabbitmq.ackMode=auto
regood.rabbitmq.retry.enable=true
regood.rabbitmq.retry.time=1000ms
regood.rabbitmq.retry.multiplier=1
regood.rabbitmq.retry.maxAttempts=3
regood.rabbitmq.retry.stateless=true
